### ISSUE TITLE
Cytosnake Logo

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CytoSnake#64]
Hi @vincerubinetti - would you be able to create a logo for our project, similar as you did for pycytominer in cytomining/pycytominer#196?

There is no rush!

**Comment by vincerubinetti** [comment]
How does this look:

![image](https://github.com/WayScience/CytoSnake/assets/8326331/a8b3368b-598e-41cf-97b1-9cc5249d14a3)

**Comment by vincerubinetti** [comment]
https://github.com/cytomining/pycytominer/issues/299

**Comment by vincerubinetti** [comment]
Closed #69
