### ISSUE TITLE
Running `cytosnake` without args throws error and does not show CLI help

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CytoSnake#70]
The README says "After this step, CytoSnake is installed. To check if CytoSnake is properly installed, simply type cytosnake to see the CLI documentation:"

But when I try, I receive the following error:

```python
(cytosnake) waygr@CHAI-M-C02G83P CytoSnake % cytosnake
Traceback (most recent call last):
  File "/Users/waygr/miniforge3/envs/cytosnake/bin/cytosnake", line 8, in <module>
    sys.exit(run_cmd())
             ^^^^^^^^^
  File "/Users/waygr/repos/wayscience/CytoSnake/cytosnake/cli/cmd.py", line 40, in run_cmd
    args_handler = CliControlPanel(sys.argv)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 10, in __init__
  File "/Users/waygr/repos/wayscience/CytoSnake/cytosnake/cli/args.py", line 110, in __post_init__
    self.__setup_args()
  File "/Users/waygr/repos/wayscience/CytoSnake/cytosnake/cli/args.py", line 235, in __setup_args
    raise InvalidArgumentException(
cytosnake.common.errors.InvalidArgumentException: No mode has been provided, please enter a mode
```

**Comment by axiomcura** [comment]
@gwaybio Thanks for submitting an issue! 

After a quick look at the code, it seems that `CytoSnake` expects a `mode`; therefore, you would have to input `cytosnake help` in order for the `CLI` documentation to appear. 

I can update the documentation by changing `cytosnake` to `cytosnake help` when attempting to test if the installation was successful. 

let me know what you think!

**Comment by gwaybio** [comment]
Updating the documentation sounds like a good plan

**Comment by axiomcura** [comment]
Closing this issue! Feel free to reopen if the problem persists.
